# Generated by Django 3.2.16 on 2023-01-05 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='testimonial')),
                ('title', models.CharField(max_length=300, unique=True)),
                ('description', models.TextField(max_length=3000, unique=True)),
                ('name', models.CharField(max_length=300, unique=True)),
                ('position', models.CharField(max_length=300)),
                ('section', models.CharField(max_length=300, unique=True)),
                ('status', models.IntegerField(choices=[(0, 'active'), (1, 'inactive')], default=0)),
                ('action', models.IntegerField(choices=[(1, 'delete'), (0, 'live')], default=0)),
            ],
        ),
    ]
