# Generated by Django 3.2.16 on 2023-01-05 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testimonial', '0002_alter_testimonial_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testimonial',
            name='action',
        ),
    ]
