# Generated by Django 3.2.16 on 2023-01-05 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testimonial', '0003_remove_testimonial_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonial',
            name='section',
            field=models.IntegerField(choices=[(1, 'slider'), (0, 'box')], default=1),
        ),
    ]
